# Generated by Django 4.2.2 on 2023-07-17 22:32

import core.service_functions.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artist Name')),
                ('slug_artist', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug Artist')),
                ('profile_url', models.CharField(blank=True, unique=True, verbose_name='Profile URL')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to=core.service_functions.services.get_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif']), core.service_functions.services.validate_size_avatar], verbose_name='Avatar')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=core.service_functions.services.get_profile_headear_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif']), core.service_functions.services.validate_size_profile_headear], verbose_name='Header Cover')),
                ('verification', models.BooleanField(default=False, verbose_name='Verification')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('follower_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Follower Counter')),
                ('following_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Following Counter')),
                ('track_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Track Counter')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('slug_track', models.SlugField(editable=False, max_length=255, verbose_name='Slug Title')),
                ('track_file', models.FileField(upload_to=core.service_functions.services.get_track_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav']), core.service_functions.services.validate_size_track], verbose_name='File')),
                ('cover_image', models.ImageField(blank=True, default=core.service_functions.services.get_default_cover_image, null=True, upload_to=core.service_functions.services.get_cover_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif']), core.service_functions.services.validate_size_cover], verbose_name='Cover')),
                ('genre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Genre')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag')),
                ('public_access', models.BooleanField(default=False, verbose_name='Public Access')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('discription', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Discription')),
                ('copy_link', models.URLField(default='', editable=False, verbose_name='Copy Link')),
                ('download_access', models.BooleanField(default=False, verbose_name='Download Access')),
                ('buy_link', models.URLField(blank=True, null=True, verbose_name='Buy Link')),
                ('play_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Play Counter')),
                ('like_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Like Counter')),
                ('repost_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Repost Counter')),
                ('comment_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Comment Counter')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Social Network')),
                ('url', models.URLField(verbose_name='Profile URL')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comment', models.TextField(max_length=2000, verbose_name='Comment')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
            options={
                'verbose_name': 'Repost',
                'verbose_name_plural': 'Reposts',
                'ordering': ('id',),
                'unique_together': {('track', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ('id',),
                'unique_together': {('track', 'artist')},
            },
        ),
    ]
