# Generated by Django 4.2.2 on 2023-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='comment_counter',
            field=models.PositiveIntegerField(default=0, editable=False, null=True, verbose_name='Comment Counter'),
        ),
        migrations.AlterField(
            model_name='track',
            name='like_counter',
            field=models.PositiveIntegerField(default=0, editable=False, null=True, verbose_name='Like Counter'),
        ),
        migrations.AlterField(
            model_name='track',
            name='play_counter',
            field=models.PositiveIntegerField(default=0, editable=False, null=True, verbose_name='Play Counter'),
        ),
        migrations.AlterField(
            model_name='track',
            name='repost_counter',
            field=models.PositiveIntegerField(default=0, editable=False, null=True, verbose_name='Repost Counter'),
        ),
    ]
