# Generated by Django 4.2.2 on 2023-07-15 21:04

import core.service_functions.services
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.service_functions.services.get_cover_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif']), core.service_functions.services.validate_size_cover], verbose_name='Cover'),
        ),
    ]
