# Generated by Django 4.2.2 on 2023-06-27 08:33

import core.service_functions.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar_link',
            field=models.ImageField(blank=True, default='site/default_logo.png', upload_to=core.service_functions.services.get_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif']), core.service_functions.services.validate_size_avatar], verbose_name='Avatar'),
        ),
    ]
