# Generated by Django 4.2.2 on 2023-07-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.track'),
        ),
    ]
