# Generated by Django 4.2.2 on 2023-06-22 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_track_comment_counter_alter_track_like_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='like',
        ),
        migrations.RemoveField(
            model_name='track',
            name='repost',
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug_artist',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_link',
            field=models.FileField(upload_to='static/media/user', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug_title',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug Title'),
        ),
    ]
