# Generated by Django 4.2.2 on 2023-07-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artist_avatar_link_alter_artist_header_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='avatar_link',
            new_name='avatar_image',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='header_link',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='cover_link',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='file_link',
            new_name='track_file',
        ),
    ]
