# Generated by Django 4.2.2 on 2023-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug_artist',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Slug Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug_title',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug Title'),
        ),
    ]
