# Generated by Django 4.2.2 on 2023-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_artist_slug_artist_alter_track_slug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug_title',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug Title'),
        ),
    ]
