# Generated by Django 4.2.2 on 2023-07-19 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_track_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='username',
        ),
        migrations.AddField(
            model_name='track',
            name='username_track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
