# Generated by Django 4.2.2 on 2023-07-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_track_username_track_username_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='username_track',
        ),
    ]
