# Generated by Django 4.2.2 on 2023-07-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_remove_track_username_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='username_like',
        ),
        migrations.AddField(
            model_name='track',
            name='username_track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
