# Generated by Django 4.2.2 on 2023-07-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_username_like_username_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username_like',
        ),
        migrations.RemoveField(
            model_name='track',
            name='username_track',
        ),
    ]
