# Generated by Django 4.2.2 on 2023-07-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_track_comment_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='like',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.track'),
        ),
    ]
