# Generated by Django 4.2.2 on 2023-07-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_comment_artist_alter_comment_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='follower_counter',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='following_counter',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='track_counter',
        ),
    ]
