export const ARTIST_ALL = "Stream [artist] music | Listen to songs, albums, playlists for free on SCCopy"   
export const ARTIST_POPULAR_TRACKS = "Stream [artist] | Listen to top hits and popular tracks online for free on SCCopy"
export const ARTIST_TRACKS = "Stream [artist] | Listen to tracks online for free on SCCopy"
export const ARTIST_ALBUMS = "Stream [artist] | Listen to music albums online for free on SCCopy"
export const ARTIST_PLAYLISTS = "Stream [artist] | Listen to music playlists online for free on SCCopy"
export const ARTIST_REPORTS = "Listen to [artist]'s favorite music online for free on SCCopy"